/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameEncargado.Ingreso.Panels;

import Biblioteca.Conexion;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class IngresarPrestamo extends javax.swing.JPanel {
 public static final String URL="jdbc:mysql://localhost:3306/biblioteca";
public static final String USERNAME="root";
public static final String PASSWORD="";
PreparedStatement ps;
PreparedStatement psEjemplar;
ResultSet rs;
ResultSet rsEjemplar;

 static int bandera=0;
public static Connection getConection(){
    Connection con = null;
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = (Connection) DriverManager.getConnection(URL,USERNAME,PASSWORD);
        System.out.println("Conexion exitosa.....");
    }
    catch(Exception ex1){
        System.out.println("Error: "+ ex1);
    }
    return con;
}
    /**
     * Creates new form IngresarUsuario
     */
    public IngresarPrestamo() {
        initComponents();
    }
 private void limpiarcajas(){
        txtcarnet.setText(null);
        txtejemplar.setText(null);
        txtFecha.setText(null);
        txtFechaDev.setText(null);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jDateComponentFactory1 = new org.jdatepicker.JDateComponentFactory();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcarnet = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtejemplar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFechaDev = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(49, 52, 67));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 52, 67));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESAR NUEVO PRESTAMO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 54, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CARNET:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));
        jPanel1.add(txtcarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 145, 126, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("EJEMPLAR:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, -1));
        jPanel1.add(txtejemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 182, 126, -1));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("FECHA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 219, 126, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("FECHA DEVOLUCION:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
        jPanel1.add(txtFechaDev, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 256, 126, -1));

        btnguardar.setText("GENERAR PRESTAMO");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 710, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
 Connection con = null;
        try {
            
            //          llamamos a la coneccion
            if(txtcarnet.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Ingrese Carnet ");
            }
            else if(txtejemplar.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Ingrese Ejemplar ");
            }else if(txtFecha.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Ingrese Fecha ");
            }else if(txtFechaDev.getText().isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Ingrese fecha devolucion ");
            }
            else if(txtcarnet.getText().length()>8){
                            JOptionPane.showMessageDialog(null, "El carnet debe tener solo 8 digitos");
            }
            else {
            con = getConection();
            ps = con.prepareStatement("SELECT carnet from usuarios where carnet = ?");
                        ps.setString(1, txtcarnet.getText());
                        rs = ps.executeQuery();
            psEjemplar = con.prepareStatement("select IdEjemplar from ejemplar where IdEjemplar = ?");
            psEjemplar.setString(1, txtejemplar.getText());
            rsEjemplar = psEjemplar.executeQuery();
            
            
            
                        
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Usuario no existe");
            }
            else if(!rsEjemplar.next())
            {
                JOptionPane.showMessageDialog(null, "Ejemplar no existe");
            }
            
            else{
                    ps = con.prepareStatement("INSERT INTO prestamos (IdUsuario, IdEjemplar,Fecha,FechaDevolucion) values (?,?,?,?)");
            ps.setString(1,txtcarnet.getText());
            ps.setString(2,txtejemplar.getText());
            ps.setString(3,txtFecha.getText());
            ps.setString(4,txtFechaDev.getText());
            
            //           fecha  ps.setDate(3, date.valueOf(txtfecha.getText()));
             int res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Prestamo Generado");
                limpiarcajas();
            }
            else{
                JOptionPane.showMessageDialog(null, "Error al generar prestamo");
                limpiarcajas();
            } 
                }
                
            
            
        }
        }
        catch(Exception e){
            System.err.println("Error: "+e);
        }
    }//GEN-LAST:event_btnguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private org.jdatepicker.JDateComponentFactory jDateComponentFactory1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaDev;
    private javax.swing.JTextField txtcarnet;
    private javax.swing.JTextField txtejemplar;
    // End of variables declaration//GEN-END:variables
}
